.safety:
  stage: security
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script:
    - pip3 install safety
  tags:
    - gitlab-org

Safety:
  extends: .safety
  script:
    - safety check --full-report

Safety stdin:
  extends: .safety
  script:
    - pip3 freeze | safety check --stdin

Trivy:
  stage: security
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
    - apk -vv info|sort
    - trivy filesystem --exit-code 1 --skip-dirs /builds/gitlab-org-forks/ --cache-dir .trivycache/ /
  tags:
    - gitlab-org

Bandit:
  stage: security
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - pip3 install bandit
    - bandit -x $(pwd)/.venv/ -r $(pwd) -s B101
  tags:
    - gitlab-org
