on:
  [push]

jobs:
  pytest:
    name: Pytest
    uses: actions/checkout@v2
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/aleksandr-kotlyar/python_and_gitlab/python-3.7.6-alpine-req:ver-14-mimesis-4.1.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_token }}
    steps:
    - run: pytest src/test/test_api.py
